version: '3.8'

services:

  mysql:
    image: mysql:8
    container_name: ecommerce-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecommerce
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: ecommerce-backend
    restart: always
    depends_on:
      - mysql
    ports:
      - "3000:3000"

  frontend:
    build: ./frontend
    container_name: ecommerce-frontend
    ports:
      - "8080:80"

# ✅ MUST be outside services
volumes:
  mysql-data:
